version: '2'
services:
  web:
    image: jefferylee/laravel
    ports:
      - "82:80"
    volumes:
      - "./:/var/www/html/"
    links:
      - "mysql:mysql"
    networks:
      - backend
  mysql:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: vue-spa
    networks:
      - backend
### Networks Setup ############################################
networks:
  backend:
    driver: "bridge"
### Volumes Setup #############################################
volumes:
  web:
    driver: "local"